[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.4.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/kevinburke/ssh_config"
  version = "0.4"

[[constraint]]
  name = "golang.org/x/crypto/ssh"
  version = "1.0"